### ISSUE TITLE
Server crashing when Stoneores2 checks for updates

### ISSUE THREAD

**Issue by Vurtipishko** [TreeboMC/StoneOres2#5]
Sometimes when i log in as OP the server crashes. 

Console log:
06.09 21:32:33 [Server] INFO [StoneOres2]Checking for updates
06.09 21:32:43 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-77 (MC: 1.15.2) ---
06.09 21:32:43 [Server] ERROR The server has not responded for 10 seconds! Creating thread dump
06.09 21:32:43 [Server] ERROR ------------------------------
06.09 21:32:43 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
06.09 21:32:43 [Server] ERROR ------------------------------
06.09 21:32:43 [Server] ERROR Current Thread: Server thread
06.09 21:32:43 [Server] ERROR PID: 32 | Suspended: false | Native: true | State: RUNNABLE
06.09 21:32:43 [Server] ERROR Stack:
06.09 21:32:43 [Server] ERROR java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
06.09 21:32:43 [Server] ERROR java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
06.09 21:32:43 [Server] ERROR java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
06.09 21:32:43 [Server] ERROR java.net.InetAddress.getAllByName0(InetAddress.java:1277)
06.09 21:32:43 [Server] ERROR java.net.InetAddress.getAllByName(InetAddress.java:1193)
06.09 21:32:43 [Server] ERROR java.net.InetAddress.getAllByName(InetAddress.java:1127)
06.09 21:32:43 [Server] ERROR java.net.InetAddress.getByName(InetAddress.java:1077)
06.09 21:32:43 [Server] ERROR java.net.InetSocketAddress.<init>(InetSocketAddress.java:220)
06.09 21:32:43 [Server] ERROR sun.net.NetworkClient.doConnect(NetworkClient.java:175)
06.09 21:32:43 [Server] ERROR sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
06.09 21:32:43 [Server] ERROR sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
06.09 21:32:43 [Server] ERROR sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
06.09 21:32:43 [Server] ERROR sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
06.09 21:32:43 [Server] ERROR sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
06.09 21:32:43 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
06.09 21:32:43 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
06.09 21:32:43 [Server] ERROR sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
06.09 21:32:43 [Server] ERROR sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
06.09 21:32:43 [Server] ERROR me.shakeforprotein.stoneores2.UpdateChecker.getCheckDownloadURL(UpdateChecker.java:45)
06.09 21:32:43 [Server] ERROR me.shakeforprotein.stoneores2.Listeners.PlayerJoinEventUpdateCheck.onPlayerJoinEvent(PlayerJoinEventUpdateCheck.java:24)
06.09 21:32:43 [Server] ERROR com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor301.execute(Unknown Source)
06.09 21:32:43 [Server] ERROR org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)

**Comment by ShakeforProtein** [comment]
What are your update settings in your config as this seems to be that it can't contact github. Also, as I've little intention of updating this as it works flawlessly for everyone else that I know are using it, I would be inclined to just disable the update checker.

**Comment by Vurtipishko** [comment]
I disabled updates right after this happened and the problem dissappeared. It's not a big issue, i have a lot of plugins on my server so it's very possible one of them is causing StoneOres2 to crash.

**Comment by ShakeforProtein** [comment]
Update checker has been removed/replaced in latest version. Whilst that won't help any with your issue (as it will effectively disable the update checker). /value and waterlogged blocks are now supported.
